export {IconHome} from './IconHome';
export {IconTransaction} from './IconTransaction';
export {IconEconomics} from './IconEconomics';
export {IconLoan} from './IconLoan';
export {IconServices} from './IconServices';
export {IconUser} from './IconUser';
export {IconInvestment} from './IconInvestment';
export {IconCreditCard} from './IconCreditCard';
export {IconSettings} from './IconSettings';
